spring:
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: localhost
  application:
    name: CUSTOMER-SERVICE

  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/customerdb
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

rabbitmq:
  queue:
    name: customer-queue
  exchange: customer-exchange
  routing-key: customer-key

server:
  port: 8081
